AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/omniauth-avaza.rb

Metrics/BlockLength:
  Exclude:
    - spec/omniauth/avaza_spec.rb
